export function preloadImages() {
  const images = [
    "/images/AtlasMountainTrekking.jpg",
    "/images/Bahia Palace.jpg",
    "/images/ChefchaouenBlueCity.jpg",
    "/images/EssaouiraCoastalCharm.jpg",
    "/images/FesCulturalImmersion.jpg",
    "/images/Jemaa el-Fnaa.jpg",
    "/images/Koutoubia Mosque.jpg",
    "/images/Majorelle Garden.jpg",
    "/images/MarrakechLuxuryRiads.jpg",
    "/images/SaharaDesertAdventures.jpg",
    "/images/Souks of Marrakech.jpg",
    "/images/ag hotel3.jpg",
    "/images/agadirstayhere.jpg",
    "/images/agadirstayhere10.jpg",
    "/images/agadirstayhere2.jpg",
    "/images/agadirstayhere3.jpg",
    "/images/agadirstayhere4.jpg",
    "/images/agadirstayhere5.jpg",
    "/images/agadirstayhere6.jpg",
    "/images/agadirstayhere7.jpg",
    "/images/agadirstayhere8.jpg",
    "/images/agadirstayhere9.jpg",
    "/images/aghotel.jpg",
    "/images/aghotel2.jpg",
    "/images/aghotel4.jpg",
    "/images/aghotel5.jpg",
    "/images/chef10.jpg",
    "/images/chef11.jpg",
    "/images/chef12.jpg",
    "/images/chef2.jpg",
    "/images/chef3.jpg",
    "/images/chef4.jpg",
    "/images/chef5.jpg",
    "/images/chef6.jpg",
    "/images/chef7.jpg",
    "/images/chef8.jpg",
    "/images/chef9.jpg",
    "/images/chefchaoun.jpg",
    "/images/chefchaounemedina.jpeg",
    "/images/kasbahmusem.jpg",
    "/images/rasslmachef.jpg",
    "/images/spainshmousque.jpg",
    "/images/Chefchaouen-local-Market.jpg",
    "/images/fes.jpg",
    "/images/fes1.jpg",
    "/images/fes2.jpg",
    "/images/fes3.jpg",
    "/images/fes4.jpg",
    "/images/fes5.jpg",
    "/images/fes6.jpg",
    "/images/fes7.jpg",
    "/images/stay here5.jpg",
    "/images/stayhere.jpg",
    "/images/stayhere1.jpg",
    "/images/stayhere2.jpg",
    "/images/stayhere3.jpg",
    "/images/stayhere4.jpg",
    "/images/stayhere6.jpg",
    "/images/stayhere7.jpg",
    "/images/stayhere8.jpg",
    "/images/stayherecasa.jpg",
    "/images/stayherecasa2.jpg",
    "/images/stayherecasa3.jpg",
    "/images/stayherecasa4.jpg",
    "/images/stayherecasa5.jpg",
    "/images/stayherecasa6.jpg",
    "/images/stayherecasa7.jpg",
    "/images/stayherecasa9.jpg",
    "/images/tanger_hiltonalhouara.jpg",
    "/images/tanger_hiltonalhouara_02.jpg",
    "/images/tanger_hiltonalhouara_1.jpg",
    "/images/tanger_hiltonalhouara_10.jpg",
    "/images/tanger_hiltonalhouara_3.jpg",
    "/images/tanger_hiltonalhouara_4.jpg",
    "/images/tanger_hiltonalhouara_5.jpg",
    "/images/tanger_hiltonalhouara_6.jpg",
    "/images/tanger_hiltonalhouara_7.jpg",
    "/images/tanger_hiltonalhouara_8.jpg",
    "/images/tanger_hiltonalhouara_9.jpg",
    "/images/zellige.jpg",
  ];
  images.forEach((src) => {
    const img = new Image();
    img.src = src;
  });
}
